version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      PORT: 3333
      HOST: localhost
      DB_CONNECTION: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3307
      MYSQL_USER: root
      MYSQL_PASSWORD: betalent
      MYSQL_DB_NAME: betalentdb
      APP_KEY: qPGUlLUZJoKXIIzrG61YFHWEW_VtL-vw
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
      - payment-gateways

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: betalentdb
      MYSQL_USER: root
      MYSQL_PASSWORD: betalent
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  payment-gateways:
    image: matheusprotzen/gateways-mock
    ports:
      - "3001:3001"
      - "3002:3002"

volumes:
  mysql-data:
